CREATE TABLE IF NOT EXISTS `rebho_custom_tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `custom_id` int(11) NOT NULL,
  `title` TEXT CHARACTER SET utf8 NOT NULL,
  `description` TEXT CHARACTER SET utf8 DEFAULT NULL,
  `status` TEXT CHARACTER SET utf8 NOT NULL,
  `add_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `last_change_date` TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
CREATE TABLE IF NOT EXISTS `rebho_custom_tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `custom_id` int(11) NOT NULL,
  `title` TEXT CHARACTER SET utf8 NOT NULL,
  `description` TEXT CHARACTER SET utf8 DEFAULT NULL,
  `add_date` datetime DEFAULT CURRENT_TIMES,
  `status` TEXT CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
);
OrderDate datetime NOT NULL DEFAULT GETDATE(
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	CURRENT_TIMESTAMP

CREATE TABLE IF NOT EXISTS `rebho_custom_tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `custom_id` int(11) NOT NULL,
  `title` TEXT CHARACTER SET utf8 NOT NULL,
  `description` TEXT CHARACTER SET utf8 DEFAULT NULL,
  `status` TEXT CHARACTER SET utf8 NOT NULL,
  `add_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `last_change_date` TIMESTAMP DEFAULT 0,
  PRIMARY KEY (`id`)
);